# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

# Pipelines > Stages > Jobs > Tasks(Steps)

jobs:
- job: Job1
  steps:
  - script: echo Hello world - Job1
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Job2
    displayName: 'Script of Job 2'
- job: Job3
  dependsOn: Job2
  steps:
  - script: echo "This is the Job 3"
    displayName: 'Script of Job 3'
- job: Job4
  dependsOn:
  - Job2
  - Job3
  steps:
  - script: |
      echo "This is the Job4"
      echo "Hello multiple lines"
    displayName: "Job4 Multiline"